apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sparkregistry.azurecr.io/redspark-io/spark-service-template/spark-service-template
  newTag: "14177856538"
resources:
- ../../base
patches:
- path: deployment.yml
- path: configmap.yml
- path: secret.yml
